### ISSUE TITLE
Error while building new firmware

### ISSUE THREAD

**Issue by RedbirdTaiwan** [OpenAcousticDevices/AudioMoth-Firmware-Basic#5]
Dear sir,
Thank you for this new and useful update version of firmware. I made a small change on the defalut filename and built successfully in an old version. But when I built this new version, it showed an error on function designFilter as the [screenshot](https://drive.google.com/file/d/1x0krSn_4MBV7spTfH2OQlimtIb8iVMqy/view?usp=sharing). How can I fix it? Thank you very much.

**Comment by alexschultze** [comment]
Your screenshot is offline.

**Comment by RedbirdTaiwan** [comment]
It works now. Thank you.
