### ISSUE TITLE
Soundfile Comment field

### ISSUE THREAD

**Issue by abfleishman** [OpenAcousticDevices/AudioMoth-Firmware-Basic#6]
The audiomoth firmware writes important info into the `comment` metadata field that is critical for attributing the sound file to a specific sound recorder.  With each release, the text that reports serial number, DateTime, temperature, battery voltage etc, has been changing.  This makes writing `regexp` to extract the info we need difficult if over the course of a project firmware was updated.

I propose that either these comments stay the same for evermore, OR the `comment` field is written as easily parsed data (json?) i.e. {"batt": "4.7V", "serial": "XXXXXX", "gain": "medium", "datetime": "YYYY-MM-DD HH:MM:SS", ...} that way it would be WAY simpler to parse.

Alternatively, these fields could be written as[ GUANO metadata](http://guano-md.org/) into the waves allowing [open-source tools](https://github.com/riggsd/guano-py) to read these pieces of info as data instead of sentences, allowing the comment field to have whatever text you want.

**Comment by abfleishman** [comment]
Specifically this line has changed https://github.com/OpenAcousticDevices/AudioMoth-Firmware-Basic/blob/master/main.c#L428

**Comment by abfleishman** [comment]
The old comment field had gain stored as an integer and the new firmware has it as a string.  What is the translation between the two?

**Comment by AlexRogersCS** [comment]
0 - Low
1 - Low-Medium
2 - Medium
3 - Medium-High
4 - High
