### ISSUE TITLE
uMoth as ultra low power microphone

### ISSUE THREAD

**Issue by dumblob** [OpenAcousticDevices/AudioMoth-Firmware-Basic#7]
I was pointed to this project. It looks awesome!

This is probably not the right place to ask, but I'm curious what is the typical (or maximum) power consumption of **uMoth** when streaming real-time recorded samples to a host over USB while acting as a microphone (i.e. without any SD card inserted, without any LED flashing, with only the minimum required filtering done on the MCU, with USB being in the "audio" isochronous mode)?

Do you think uMoth could be max 35mA?

**Comment by AlexRogersCS** [comment]
We haven't measured it but probably around 10-15mA.
