### ISSUE TITLE
2 microphones on 1 uMoth

### ISSUE THREAD

**Issue by dumblob** [OpenAcousticDevices/AudioMoth-Firmware-Basic#8]
I wonder whether uMoth could be extended to drive 2 microphones and then stream from both simultaneously over USB "audio" isochronous connection to a USB host (i.e. acting either as a stereo USB microphone or two mono USB microphones)?

If it's possible, how much would this extension affect the overall power consumption (I'm interested in the power budget discussed in https://github.com/OpenAcousticDevices/AudioMoth-Firmware-Basic/issues/7 ).

**Comment by AlexRogersCS** [comment]
The software would support stereo USB microphones but not the hardware at the moment.

**Comment by dumblob** [comment]
Ok, thanks.

What channels shall I follow to get notified about HW support of stereo USB microphones (or two mono microphones over one USB port)?

This repo? Or some RSS? Or some mailing list?

**Comment by AlexRogersCS** [comment]
Sign-up to the mailing list on the main website - https://www.openacousticdevices.info and the forum there. We use the github repositories for publishing and don't respond to contact here very regularly.
